CREATE TYPE "modalidade_pagamento_enum" AS ENUM (
  'mensal',
  'semanal'
);

CREATE TYPE "status_entrega_enum" AS ENUM (
  'enviado',
  'avaliado',
  'entregue_com_atraso',
  'reenvio_solicitado'
);

CREATE TYPE "status_boleto_enum" AS ENUM (
  'pendente',
  'pago',
  'vencido',
  'cancelado',
  'estornado'
);

CREATE TYPE "status_aula_enum" AS ENUM (
  'agendada',
  'realizada',
  'cancelada'
);

CREATE TYPE "tipo_usuario_enum" AS ENUM (
  'aluno',
  'professor'
);

CREATE TABLE "usuario" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_completo" varchar(100) NOT NULL,
  "email" varchar(80) UNIQUE NOT NULL,
  "senha" varchar(150), -- hash Argon2id; nulo até o primeiro acesso
  "tipo" tipo_usuario_enum NOT NULL, -- (professor, aluno)
  "versao_token" integer NOT NULL DEFAULT 0,
  "tentativas_login" integer NOT NULL DEFAULT 0,
  "bloqueado_ate" timestamptz,
  "criado_em" timestamptz NOT NULL DEFAULT (now()),
  "atualizado_em" timestamptz NOT NULL DEFAULT (now()),
  "deletado_em" timestamptz
);

CREATE TABLE "aluno" (
  "usuario_id" integer PRIMARY KEY,
  "data_nascimento" date NOT NULL,
  "possui_responsavel" boolean NOT NULL,
  "cpf" varchar(11) UNIQUE,
  "telefone" varchar(11),
  "responsavel_nome" varchar(100),
  "responsavel_cpf" varchar(11), -- sem UNIQUE: irmãos podem ter o mesmo responsável
  "responsavel_telefone" varchar(11),
  "modalidade" modalidade_pagamento_enum, -- ainda não implementado na API
  "criado_em" timestamptz NOT NULL DEFAULT (now()),
  "atualizado_em" timestamptz NOT NULL DEFAULT (now()),
  "deletado_em" timestamptz,
  -- Menor de idade: só os dados do responsável. Maior: só os do aluno.
  CONSTRAINT "ck_aluno_dados_do_responsavel" CHECK (
    (possui_responsavel AND responsavel_nome IS NOT NULL
      AND responsavel_cpf IS NOT NULL AND responsavel_telefone IS NOT NULL
      AND cpf IS NULL AND telefone IS NULL)
    OR (NOT possui_responsavel AND cpf IS NOT NULL AND telefone IS NOT NULL
      AND responsavel_nome IS NULL AND responsavel_cpf IS NULL
      AND responsavel_telefone IS NULL)
  )
);

CREATE TABLE "professor" (
  "usuario_id" integer PRIMARY KEY,
  "cnpj" varchar(14) UNIQUE,
  "chave_pix" varchar(15) UNIQUE
);

-- Códigos de convite (primeiro acesso) e de redefinição de senha
CREATE TABLE "codigo_verificacao" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "codigo_hash" varchar(64) NOT NULL,
  "expira_em" timestamptz NOT NULL,
  "tentativas" integer NOT NULL DEFAULT 0,
  "usado_em" timestamptz,
  "criado_em" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "aula" (
  "id" integer PRIMARY KEY,
  "titulo" varchar(75),
  "descricao" varchar(150),
  "data" date,
  "hr_inicio" time,
  "hr_fim" time,
  "anotacoes" text,
  "status" status_aula_enum,
  "professor_id" integer NOT NULL
);

CREATE TABLE "aula_aluno" (
  "aula_id" integer NOT NULL,
  "aluno_id" integer NOT NULL,
  "data_inscricao" timestamp DEFAULT (now()),
  PRIMARY KEY ("aula_id", "aluno_id")
);

CREATE TABLE "grupo" (
  "id" integer PRIMARY KEY,
  "aluno_id" integer,
  "professor_id" integer NOT NULL,
  "titulo" varchar(50),
  "descricao" varchar(100)
);

CREATE TABLE "recado" (
  "id" integer PRIMARY KEY,
  "titulo" varchar(50),
  "descricao" text,
  "professor_id" integer NOT NULL
);

CREATE TABLE "atividade" (
  "id" integer PRIMARY KEY,
  "titulo" varchar(70),
  "descricao" text,
  "dt_abertura" timestamp DEFAULT (now()),
  "dt_limite" timestamp NOT NULL,
  "pontuacao_maxima" decimal(4,2),
  "is_agendado" boolean,
  "data_agendada" date,
  "hr_agendada" time,
  "professor_id" integer NOT NULL
);

CREATE TABLE "anexo_atividade" (
  "id" integer PRIMARY KEY,
  "atividade_id" integer NOT NULL,
  "nome_arquivo" varchar(150) NOT NULL,
  "drive_file_id" varchar(100) UNIQUE,
  "drive_url" varchar(255) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "entrega_atividade" (
  "id" integer PRIMARY KEY,
  "atividade_id" integer NOT NULL,
  "aluno_id" integer NOT NULL,
  "drive_file_id" varchar(100) UNIQUE,
  "drive_url" varchar(255) UNIQUE NOT NULL,
  "comentarios" text,
  "dt_envio" timestamp DEFAULT (now()),
  "nota" decimal(4,2),
  "feedback_professor" text,
  "status" status_entrega_enum DEFAULT 'enviado'
);

CREATE TABLE "fatura" (
  "id" integer PRIMARY KEY,
  "dt_vencimento" date,
  "dt_pagamento" date,
  "valor_pagar" decimal(6,2),
  "valor_recebido" decimal(6,2),
  "recibo" varchar UNIQUE,
  "status" status_boleto_enum,
  "aluno_id" integer NOT NULL
);

CREATE INDEX "ix_codigo_verificacao_usuario_id" ON "codigo_verificacao" ("usuario_id");

CREATE UNIQUE INDEX ON "entrega_atividade" ("atividade_id", "aluno_id");

COMMENT ON COLUMN "aula_aluno"."data_inscricao" IS 'Data/hora do vínculo';

COMMENT ON COLUMN "anexo_atividade"."drive_file_id" IS 'ID do arquivo no Google Drive';

COMMENT ON COLUMN "anexo_atividade"."drive_url" IS 'Link de visualização/download';

COMMENT ON COLUMN "entrega_atividade"."drive_file_id" IS 'ID do arquivo enviado pelo aluno';

COMMENT ON COLUMN "entrega_atividade"."drive_url" IS 'Link do arquivo no Drive do aluno';

ALTER TABLE "codigo_verificacao" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") ON DELETE CASCADE;

ALTER TABLE "aluno" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") ON DELETE CASCADE;

ALTER TABLE "professor" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") ON DELETE CASCADE;

ALTER TABLE "aula" ADD FOREIGN KEY ("professor_id") REFERENCES "professor" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recado" ADD FOREIGN KEY ("professor_id") REFERENCES "professor" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aula_aluno" ADD FOREIGN KEY ("aula_id") REFERENCES "aula" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aula_aluno" ADD FOREIGN KEY ("aluno_id") REFERENCES "aluno" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "grupo" ADD FOREIGN KEY ("professor_id") REFERENCES "professor" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "grupo" ADD FOREIGN KEY ("aluno_id") REFERENCES "aluno" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fatura" ADD FOREIGN KEY ("aluno_id") REFERENCES "aluno" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "atividade" ADD FOREIGN KEY ("professor_id") REFERENCES "professor" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anexo_atividade" ADD FOREIGN KEY ("atividade_id") REFERENCES "atividade" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entrega_atividade" ADD FOREIGN KEY ("atividade_id") REFERENCES "atividade" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entrega_atividade" ADD FOREIGN KEY ("aluno_id") REFERENCES "aluno" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;
